### ISSUE TITLE
Enforce filename format

### ISSUE THREAD

**Issue by jrunning** [Banno/ux-lint#37]
We should enforce kebab-case filenames [per our style guide](https://docs.banno.com/ux/CodeStyle/#filesystem-structure). [sindresorhus/eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn) has a [filename-case](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/filename-case.md) rule that can do this for JavaScript files. Perhaps we could write an analogous HTMLHint rule.

**Comment by eheikes** [comment]
This is a duplicate of #6 -- but that's nice plugin link.
